#print("\033[1;32;40m")
#print("╔"+"═"*20+"╗")
print("╔═════════════════════╗")
#print("║\033[1;31;40m   HESAP MAKİNESİ  \033[1;32;40m  ║")
print("║   VEKTOREL APP      ║")
print("║                     ║")
print("║  1-Hesap makinesi   ║")
print("║  1-Çizimler         ║")
print("║  1-Oyunlar          ║")
print("║  1-Sağlık apps      ║")
print("║  3-                 ║")
print("║  4-                 ║")
print("║                     ║")
print("║    Seçimiz nedir?   ║")
print("╚═════════════════════╝")
